### PR TITLE
Add dependabot for the sub-projects as well

### PR DESCRIPTION
**Pull request by sebastiaanspeck**

### CODE REVIEW

**Comment by StevenLooman** [comment]
I'm not entirely sure this does anything, as all versions are pinned on the top project. But we'll see what happens.

**Comment by sebastiaanspeck** [comment]
> I'm not entirely sure this does anything, as all versions are pinned on the top project. But we'll see what happens.

It does too much.. I hoped dependabot was a bit smarter to notice it already opened a PR to bump a dependency in the top-level pom.xml.

**Comment by StevenLooman** [comment]
Please create a PR to revert this.

**Comment by StevenLooman** [comment]
Never mind, already reverted it.

**Pull request merged**
