### PR TITLE
Only limit if maxInfractions is not null

### PR DESCRIPTION
**Pull request by sebastiaanspeck**

### CODE REVIEW

**Comment by StevenLooman** [comment]
Thank you for this PR @sebastiaanspeck. Do you have any concrete examples why this would be needed? I.e., do you have a project with more than `9,223,372,036,854,775,807` issues?

**Comment by sebastiaanspeck** [comment]
Right now the resulting `magik-lint.jar` fails, due to the fact that `.limit()` does not work if `maxInfractions` is null. Initially I thought of setting `maxInfractions` by default to e.g. 400, but AFAIK we did not have a limit set to `maxInfractions` until now. Therefore I went for this approach. E.g. `flycheck` has a variable `flycheck-checker-error-threshold` which is set to 2254, but that is a threshold per file.

**Comment by StevenLooman** [comment]
Ah, indeed. I have fixed it with https://github.com/StevenLooman/magik-tools/commit/e8a3db5d413b9b51b7ddd65d781f7a01fcc70c2f. This is more in line with the general use of `MagikToolsProperties` and causes less complexity in `MagikLint.run()`.

**Comment by StevenLooman** [comment]
Thank you for bringing this up!

**Comment by sebastiaanspeck** [comment]
No problem, you could refactor https://github.com/StevenLooman/magik-tools/blob/e8a3db5d413b9b51b7ddd65d781f7a01fcc70c2f/magik-lint/src/main/java/nl/ramsolutions/sw/magik/lint/output/MessageFormatReporter.java#L45 by changing this line https://github.com/StevenLooman/magik-tools/blob/e8a3db5d413b9b51b7ddd65d781f7a01fcc70c2f/magik-lint/src/main/java/nl/ramsolutions/sw/magik/lint/Main.java#L131 to use the new `getPropertyLong(MagikLint.KEY_COLUMN_OFFSET, 0L)`.

**Comment by StevenLooman** [comment]
Indeed, thanks!

**Pull request closed without merging**
