### PR TITLE
Add UnsafeEvaluateInvocation check to Sonar way profile

### PR DESCRIPTION
**Pull request by sebastiaanspeck**

### CODE REVIEW

**Comment by sebastiaanspeck** [comment]
Looking into this, the magik-types-checks aren't shown in Sonar right now. Shouldn't they be added to a Sonar_way_profile.json as well?

**Comment by StevenLooman** [comment]
> Looking into this, the magik-types-checks aren't shown in Sonar right now. Shouldn't they be added to a Sonar_way_profile.json as well?

No, the magik-types-checks require reasoning about the typing of expressions etc and a proper type database. It is too soon to add this to Sonar.

**Comment by StevenLooman** [comment]
Thanks!

**Comment by sebastiaanspeck** [comment]
> > Looking into this, the magik-types-checks aren't shown in Sonar right now. Shouldn't they be added to a Sonar_way_profile.json as well?
> 
> No, the magik-types-checks require reasoning about the typing of expressions etc and a proper type database. It is too soon to add this to Sonar.

Sad. There are several checks very useful (e.g. deprecated method usage).

**Comment by StevenLooman** [comment]
No need to be sad. You can use the magik-typed-linter for this.

**Pull request merged**
