### PR TITLE
Extend FormattingCheck to require at most 2 successive empty lines

### LINKED ISSUE #39: Raise an issue for multiple newlines
```
1 _package user
2 
3 
4 def_slotted_exemplar(:a, {})
5 $
6 
7 _method a.b()
8 _endmethod
9 $
10 
11 _method a.c()
12 	a.do_something()
13 _endmethod
14 $
15
16
17 _method a.d
18 _endmethod
19 $
20 
21 
22 _method a.e
23 	a.do_something_else()
24 _endmethod
25 $
```

Looking at the code snippet above, it would be nice if the `magik-lint` would raise issues for multiple newlines on lines 3, 16 and 21. A single newline is sufficient for Magik. Extra newlines only creates clutter and doesn't encourage a uniform code style.

### PR DESCRIPTION
**Pull request by StevenLooman**
Extend FormattingCheck to require at most 2 successive empty lines

Fixes #39.

### CODE REVIEW

**Comment by StevenLooman** [comment]
@sebastiaanspeck Can you test if this works for you?

**Comment by sebastiaanspeck** [comment]
I will test this on Friday for you if that's okay.

**Comment by sebastiaanspeck** [comment]
I found some spare time to quickly test it this morning. 
At first it seemed to work like a charm, but when testing the code block below, it also raises an issue for line 12: `>> parameter + 1`. In the code block below I would expect 3 issues; line 3, line 26 and line 32.

```
_package user


def_slotted_exemplar(:a, {})
$

_method a.a(parameter)
	##
	## PARAMETER is used...
	##

	>> parameter + 1
_endmethod
$

_method a.b
	a.do_something
_endmethod
$

_method a.c()
	a.do_something()
_endmethod
$


_method a.d
	a.do_something_elsee
_endmethod
$


_method a.e
	a.do_something_else()
_endmethod
$
```

The issue itself is raised a line below the actual line that introduces the second newline:
image

**Comment by StevenLooman** [comment]
Can you try again?

**Comment by sebastiaanspeck** [comment]
Looks better!
image

Is it possible to mark the second newline as the issued line? Instead of the third line.

**Comment by sebastiaanspeck** [comment]
Or the last newline:
image

You get multiple issues for the same block. Would have expected that line 6 was marked, but not line 7 4 times.

**Comment by StevenLooman** [comment]
Can you test the last change?

**Comment by sebastiaanspeck** [comment]
Looks better, but it still raises multiple issues for the first block. I would have expected just one issue on line 6, but maybe that is a nice to have, although the whitespace-checking also doesn't trigger twice if you got the next line:
`def_slotted_exemplar(  :a, {})`.

image

**Comment by StevenLooman** [comment]
I'm not sure if SonarQube handles multi-line issues properly. I'll test this later. If SonarQube does handle it properly, then I'll change it.

**Comment by sebastiaanspeck** [comment]
Given these lines:
```
$



_pragma(classify_level=basic)
_method a.a(parameter)
```

the check won't trigger. As soon as I remove the `_pragma`-line, the check triggers.

**Comment by StevenLooman** [comment]
Can you try again? Admittedly, this is a bit of a blind commit so expect some things to not work properly. :)

**Comment by StevenLooman** [comment]
Can you try again? Admittedly, this is a bit of a blind commit so expect some things to not work properly. :)

**Comment by sebastiaanspeck** [comment]
I will test it tomorrow 👍🏻  the branch needs a good rebase as well

**Comment by sebastiaanspeck** [comment]
LGTM!

image

It issues the first line in the list, but it stretches the issue until the last empty line, which is as desired.
It also triggers on lines with a pragma.

I will test this branch in my daily work to see if I find any issues.

**Comment by StevenLooman** [comment]
Ship it! (just kidding)

Thank you for testing. I plan to release `0.8.2` soon which will be a release containing only fixes. I'll test a bit myself too.

Then, later this year, I plan to release `0.9.0` which will include more changes, including this, and other things I'm currently working on.

**Pull request merged**
