### PR TITLE
publish-checks-wiki: setup Python and remove commented code

### PR DESCRIPTION
**Pull request by sebastiaanspeck**
A little note I too want to mention. Even if nothing changed, this workflow will create a new empty commit to the Wiki

### CODE REVIEW

**Comment by StevenLooman** [comment]
Thank you for this PR @sebastiaanspeck. On (at least) Debian based distros, such as Ubuntu, it is "standard" to use `python3` instead of `python`. I cannot find the source where I read/heard this. Perhaps [PEP394](https://peps.python.org/pep-0394/) does shed some light on this. You are right of course, that nobody will be using (or at least should be using) Python2 these days!

Also, the `#dry-run: true` was left there to show my future self (and others) that it is possible to do a dry run.

> A little note I too want to mention. Even if nothing changed, this workflow will create a new empty commit to the Wiki

Yes, this is true and certainly a downside. Yet, I find the downside acceptable compared to writing an action myself as this would certainly cost more time.

In the end, thank you for this PR, but I don't see the need to merge this. I am glad you trying to find improvements though!

**Comment by sebastiaanspeck** [comment]
> Thank you for this PR @sebastiaanspeck. On (at least) Debian based distros, such as Ubuntu, it is "standard" to use `python3` instead of `python`. I cannot find the source where I read/heard this. Perhaps [PEP394](https://peps.python.org/pep-0394/) does shed some light on this. You are right of course, that nobody will be using (or at least should be using) Python2 these days!

The reason I changed it, was that you can combine the two `python3` commands into one. Was not fully aware I changed it from `python3` to `python`.

**Comment by StevenLooman** [comment]
I noticed this too but I don't see any advantage or disadvantage to it. There isn't going to be any additional "layer" like in Docker. The overhead is minimal and it's not going to be ran that often anyway.

**Comment by StevenLooman** [comment]
To add, I expect this to change in the future, when perhaps a v5 of the `Andrew-Chen-Wang/github-wiki-action` is released (if ever.)

**Pull request closed without merging**
