### PR TITLE
Also analyse PR's with Sonar

### PR DESCRIPTION
**Pull request by sebastiaanspeck**

### CODE REVIEW

**Comment by StevenLooman** [comment]
Why did you close it?

**Comment by sebastiaanspeck** [comment]
> Why did you close it?

Because the pipeline failed, so I thought this isn't something that would work.

**Comment by StevenLooman** [comment]
I see. This is because you need a token. The token is supposed to be secret and is only available in this repository. Otherwise you'd be able to create a PR with a modified action and extract the token.

**Comment by StevenLooman** [comment]
I don't think the `sonar_cloud` action should be ran from a PR, even partially. It doesn't do anything new compared to the other actions; it mostly does duplicate work without any actionable results, thus wasting run time.

**Comment by sebastiaanspeck** [comment]
I hoped it would show the PR's in SonarCloud to detect any issues, but it is okay for me to just close this one.

**Comment by StevenLooman** [comment]
If you want any feedback during development, you can use SonarLint.

**Pull request closed without merging**
